#!/usr/bin/env bun
/**
 * Generate Virtual Filesystem module from src/skills/
 *
 * Walks all skill directories and generates a TypeScript module
 * that exports skill content as in-memory data. Used by compiled
 * binaries where filesystem discovery doesn't work.
 *
 * Output: src/cli/generated/skills-vfs.ts
 */

import { readdirSync, existsSync, mkdirSync } from 'fs';
import { join, relative } from 'path';

// Dual root: public shelf (skills/, post-move) + vault (src/skills/ —
// secrets; .archive is now just a breadcrumb). Shelf tolerated absent pre-move.
const SHELF_DIR = join(import.meta.dir, '..', 'skills');
const VAULT_DIR = join(import.meta.dir, '..', 'src', 'skills');
const OUTPUT_DIR = join(import.meta.dir, '..', 'src', 'cli', 'generated');
const OUTPUT_FILE = join(OUTPUT_DIR, 'skills-vfs.ts');

function walkDir(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === '.DS_Store') continue;
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDir(fullPath));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

// Discover skill directories (same logic as discoverSkills in skill-source.ts)
const listDirs = (root: string) =>
  existsSync(root)
    ? readdirSync(root, { withFileTypes: true })
        .filter((d) => d.isDirectory() && !d.name.startsWith('.') && d.name !== '_template')
        .map((d) => ({ name: d.name, dir: join(root, d.name) }))
    : [];

const shelfDirs = listDirs(SHELF_DIR);
const vaultDirs = listDirs(VAULT_DIR);

// src/skills/.archive/ held zombie skills, bundled so compiled-binary
// `install -s <name>` worked offline. They moved to
// Soul-Brews-Studio/arra-oracle-skills-archive on 2026-08-22, so this now
// resolves to nothing. The scan is kept for a future retirement.
const archivedDirs = listDirs(join(VAULT_DIR, '.archive'));

const skillDirs = [...shelfDirs, ...vaultDirs, ...archivedDirs].sort((a, b) => a.name.localeCompare(b.name));

// A duplicate name across roots would silently last-wins in the VFS Map —
// fail the build instead (same invariant compile.ts + discoverSkills enforce).
{
  const seen = new Map<string, string>();
  for (const { name, dir } of skillDirs) {
    const prev = seen.get(name);
    if (prev) throw new Error(`Duplicate skill name "${name}" across roots: ${prev} and ${dir}`);
    seen.set(name, dir);
  }
}

const skillNames = skillDirs.map((s) => s.name);

// Build VFS data
const entries: string[] = [];

for (const { name: skillName, dir: skillDir } of skillDirs) {
  const files = walkDir(skillDir);

  const fileEntries: string[] = [];
  for (const filePath of files) {
    const relPath = relative(skillDir, filePath);
    const content = await Bun.file(filePath).text();
    // Escape backticks and ${} for template literals
    const escaped = content
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$\{/g, '\\${');
    fileEntries.push(`    [${JSON.stringify(relPath)}, \`${escaped}\`]`);
  }

  entries.push(`  [${JSON.stringify(skillName)}, new Map([\n${fileEntries.join(',\n')}\n  ])]`);
}

// Generate output
const output = `// Auto-generated by scripts/generate-vfs.ts — DO NOT EDIT
// Generated at: ${new Date().toISOString()}
// Skills: ${skillDirs.length}, Files: ${entries.reduce((n, e) => n + (e.match(/\["/g) || []).length, 0)}

export const SKILLS_VFS: Map<string, Map<string, string>> = new Map([
${entries.join(',\n')}
]);

export const SKILL_NAMES: string[] = ${JSON.stringify(skillNames)};
`;

// Ensure output directory exists
if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

await Bun.write(OUTPUT_FILE, output);

const totalFiles = skillDirs.reduce((sum, s) => sum + walkDir(s.dir).length, 0);

console.log(`Generated VFS: ${skillDirs.length} skills, ${totalFiles} files → ${OUTPUT_FILE}`);
